name: "test_ci"

on:
  push:
    branches: [test]
  # pull_request:
  #   branches: [master]
  #   types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    container: astral/uv:python3.12-bookworm-slim
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: "Install dependencies"
        run: cd python && uv sync
      - name: "Run tests"
        run: cd python && uv run pytest test/